# Generated by Django 5.0.3 on 2024-03-21 08:20

import ckeditor.fields
import core.models
import django_ckeditor_5.fields
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=200, null=True)),
                ("city", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=150, null=True)),
                ("street_name", models.CharField(max_length=200, null=True)),
                ("mobile", models.CharField(max_length=200, null=True)),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Address",
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookmarkJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=200)),
                ("product_status", models.CharField(max_length=200)),
                ("item", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=9.99, max_digits=999999999
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=9.99, max_digits=999999999
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cart Order Items",
            },
        ),
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=9.99, max_digits=999999999
                    ),
                ),
                ("paid_status", models.BooleanField(default=False)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                        ],
                        default="processing",
                        max_length=40,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cart Order",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoryId",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="12345abcdefghi",
                        length=10,
                        max_length=20,
                        prefix="CAT",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Food stuff", max_length=100)),
                (
                    "image",
                    models.ImageField(default="category.jpg", upload_to="category"),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=150)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Us",
            },
        ),
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expertId",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="12345abcdefghi",
                        length=10,
                        max_length=20,
                        prefix="expert",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Full Name")),
                (
                    "profession",
                    models.CharField(max_length=100, verbose_name="Profession"),
                ),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="expert.jpg", upload_to=core.models.user_directory_path
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
                ),
                ("address", models.CharField(default="Busia, Kenya", max_length=100)),
                ("contact", models.CharField(default="+254740298531", max_length=100)),
                ("chat_response_time", models.CharField(default="100", max_length=100)),
                ("authentic_rating", models.CharField(default="98", max_length=100)),
            ],
            options={
                "verbose_name_plural": "Experts",
            },
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farmerId",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="12345abcdefghi",
                        length=10,
                        max_length=20,
                        prefix="farm",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Digify farmer", max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="farmer.jpg", upload_to=core.models.user_directory_path
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        default="farmer.jpg", upload_to=core.models.user_directory_path
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                ("address", models.CharField(default="Busia, Kenya", max_length=100)),
                ("contact", models.CharField(default="+254740298531", max_length=100)),
                ("chat_response_time", models.CharField(default="100", max_length=100)),
                ("shipping_on_time", models.CharField(default="100", max_length=100)),
                ("authentic_rating", models.CharField(default="98", max_length=100)),
                ("days_return", models.CharField(default="7", max_length=100)),
                ("warranty_period", models.CharField(default="4", max_length=100)),
                ("twitter", models.URLField(blank=True, max_length=500, null=True)),
                ("facebook", models.URLField(blank=True, max_length=500, null=True)),
                ("instagram", models.URLField(blank=True, max_length=500, null=True)),
                ("pinterest", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name_plural": "Farmers",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", ckeditor.fields.RichTextField()),
                ("location", models.CharField(max_length=300)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("1", "Full time"),
                            ("2", "Part time"),
                            ("3", "Internship"),
                        ],
                        max_length=1,
                    ),
                ),
                ("salary", models.CharField(blank=True, max_length=30)),
                ("company_name", models.CharField(max_length=300)),
                (
                    "company_description",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                ("url", models.URLField()),
                ("last_date", models.DateField()),
                ("is_published", models.BooleanField(default=False)),
                ("is_closed", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "productId",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="12345abcdefghi",
                        length=10,
                        max_length=20,
                        prefix="prd",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Fresh vegetables", max_length=150)),
                (
                    "image",
                    models.ImageField(
                        default="product.jpg", upload_to=core.models.user_directory_path
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=9.99, max_digits=999999999
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, default=19.99, max_digits=999999999
                    ),
                ),
                (
                    "specification",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Specification"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, default="Organic product", max_length=100, null=True
                    ),
                ),
                (
                    "stock_count",
                    models.CharField(
                        blank=True, default="5", max_length=100, null=True
                    ),
                ),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("disabled", "disabled"),
                            ("rejected", "Rejected"),
                            ("in_review", "In review"),
                            ("published", "Published"),
                        ],
                        default="in_review",
                        max_length=10,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("digital", models.BooleanField(default=False)),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=5,
                        max_length=10,
                        prefix="sku",
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        default="product.jpg", upload_to="product-images"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        default=None,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Product Reviews",
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Wishlist",
            },
        ),
    ]
