# Generated by Django 5.0.1 on 2024-02-13 16:26

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='12345abcdefghi', length=10, max_length=20, prefix='CAT', unique=True),
        ),
    ]
