# Generated by Django 5.0.3 on 2024-04-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="coupons",
            field=models.ManyToManyField(blank=True, to="core.coupon"),
        ),
    ]
