# Generated by Django 5.0.1 on 2024-02-17 12:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_farmer_date_alter_product_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='cover_image',
            field=models.ImageField(default='farmer.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
