# Generated by Django 5.0.3 on 2024-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_cartorder_oid"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="facebook",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="expert",
            name="instagram",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="expert",
            name="pinterest",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="expert",
            name="twitter",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
