# Generated by Django 5.0.1 on 2024-02-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(blank=True, default='5', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='Organic product', max_length=100, null=True),
        ),
    ]
