# Generated by Django 5.0.1 on 2024-02-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_stock_count_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='days_return',
            field=models.CharField(default='7', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='warranty_period',
            field=models.CharField(default='4', max_length=100),
        ),
    ]
