# Generated by Django 5.0.1 on 2024-02-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_farmer_days_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='authentic_rating',
            field=models.CharField(default='98', max_length=100),
        ),
    ]
