# Generated by Django 5.0.1 on 2024-02-19 21:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='I am a great farmer', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Specifications', null=True),
        ),
    ]
