# Generated by Django 5.0.1 on 2024-02-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_address_mobile_alter_cartitems_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
