"""
Django settings for emarketproject project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gb_lf1ys)n24*!iibyhcy)brl0p6a-5*9b&)jglnsjb0x2g^$+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # created apps
    'core',
    'userauths',


    # Third party
    'taggit',
    # 'ckeditor',
    'ckeditor',

    # paypal payment integration
    'paypal.standard.ipn',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'emarketproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'core.context_processor.default',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'emarketproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    'site_header': 'AgriEmpower Africa',
    'site_logo': 'assets/imgs/logo/download.svg',
    'site_brand': 'Growth beyond borders',
    # 'site_brand': 'AgriEmpower Africa',
    'site_copyright': 'agriempowerafrica.com/'
}


AUTH_USER_MODEL = 'userauths.User'
LOGIN_URL = 'userauths:signIn'

CKEDITOR_UPLOAD_PATH = 'uploads/'


CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'codeSnippet_theme':'monokai',
        'toolbar': 'all',
        'extraPlugins': ','.join([
            'codesnippet',  # panels
            'widget',
            'dialog'
        ]),

}
}


PAYPAL_RECEIVER_EMAIL = 'digifarm497@gmail.com'
PAYPAL_TEST = True
# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'Full',
#         'extraPlugins': ','.join([
#             'image2',  # register the image2 plugin
#             'uploadfile',  # register the uploadfile plugin on the toolbar
#         ]),
#     },
# }

# LOGIN_REDIRECT_URL = 'dashboard'
# LOGOUT_REDIRECT_URL = 'login'

# CRISPY_TEMPLATE_PACK = 'bootstrap5'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_PORT = config('EMAIL_PORT')
# EMAIL_USE_TLS = True
# EMAIL_FROM = config("EMAIL_FROM")
# SERVER_EMAIL = EMAIL_FROM

# ACCOUNT_ACTIVATION_DAYS = 7
# REGISTRATION_OPEN = False
# # RECAPTCHA_PUBLIC_KEY = config('GOOGLE_RECAPTCHA_PUBLIC_KEY')
# # RECAPTCHA_PRIVATE_KEY = config('GOOGLE_RECAPTCHA_PRIVATE_KEY')

# # Django AllAuth Configurations
# SOCIALACCOUNT_PROVIDERS = {
#     'facebook': {
#         'MESSAGE': ('Your social media account is not yet linked.'
#                     ' Please go to your profile page and link it with us'),
#         'SCOPE': ['email'],
#         'OPTIONS': {'fields': ['id', 'name', 'email']},
#         'EXCEPTION_HANDLER': lambda r: None,
#     }
# }

# AUTHENTICATION_BACKENDS = (
#     'social_core.backends.open_id.OpenIdAuth',  # for Google authentication
#     'social_core.backends.google.GoogleOpenIdAuth',  # for Google authentication
#     'social_core.backends.google.GoogleOAuth2',  # for Google Oauth2
#     'django.contrib.auth.backends.ModelBackend',
# )

# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

# SOCIAL_AUTH_FACEBOOK_KEY = config('SOCIAL_AUTH_FACEBOOK_KEY')
# SOCIAL_AUTH_FACEBOOK_SECRET = config('SOCIAL_AUTH_FACEBOOK_SECRET') /

# SOCIAL_AUTH_PIPELINE = (
#    'social_core.pipeline.social_auth.social_details',
#    'social_core.pipeline.social_auth.social_uid',
#    'social_core.pipeline.social_auth.social_user',
#    'social_core.pipeline.user.get_username',
#    'social_core.pipeline.user.create_user',
#    'social_core.pipeline.user.save_user',
#    'social_core.pipeline.social_auth.associate_user',
#    'social_core.pipeline.social_auth.load_extra_data',
#    'social_core.pipeline.user.user_details'
# )



# LOGOUT_URL = '/logout/'